# Generated by Django 4.0.5 on 2022-06-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opisanie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='parents',
            field=models.IntegerField(verbose_name='Номер родителей ученика'),
        ),
    ]
