# Generated by Django 4.0.5 on 2022-06-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opisanie', '0002_alter_students_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='clas_num',
            field=models.IntegerField(verbose_name='Номер класса'),
        ),
    ]
